name: 'test my project'
on:
  push:

jobs:
  test-job:
    runs-on: Ubuntu 20.04.3
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
    
    - name: 'test'
      run: make lint